### PR TITLE
fix(cli): win EOL conversion for gen templates

### LINKED ISSUE #2253: Ignite generators don't work on Windows
### Describe the bug

When generating a screen with a command such as `npx ignite-cli generate screen TestScreen`, the frontmatter gets left in if executing from a Windows machine. For example:

```
---
patch:
  path: "app/screens/index.ts"
  append: "export * from \"./TestScreen\"\n"
  skip: 
---
import React, { FC } from "react"
import { observer } from "mobx-react-lite"
import { ViewStyle } from "react-native"
import { StackScreenProps } from "@react-navigation/stack"
import { AppStackScreenProps, AppStackParamList } from "../navigators"
import { Screen, Text } from "../components"
// import { useNavigation } from "@react-navigation/native"
// import { useStores } from "../models"

// STOP! READ ME FIRST!
// To fix the TS error below, you'll need to add the following things in your navigation config:
// - Add `Test: undefined` to AppStackParamList
// - Import your screen, and add it to the stack:
//     `<Stack.Screen name="Test" component={TestScreen} />`
// Hint: Look for the 🔥!

// REMOVE ME! ⬇️ This TS ignore will not be necessary after you've added the correct navigator param type
// @ts-ignore
export const TestScreen: FC<StackScreenProps<AppStackScreenProps, "Test">> = observer(function TestScreen() {
  // Pull in one of our MST stores
  // const { someStore, anotherStore } = useStores()

  // Pull in navigation via hook
  // const navigation = useNavigation()
  return (
    <Screen style={$root} preset="scroll">
      <Text text="test" />
    </Screen>
  )
})

const $root: ViewStyle = {
  flex: 1,
}
```

Fix the new line parsing based on the platform we're executing on to allow generators to be cross-platform

### Ignite version

8.2.0

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                16 cores        Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
  directory          GeneratorTest   C:\temp\GeneratorTest

JavaScript (and globally-installed packages)
  node                16.14.2      C:\Program Files\nodejs\node.EXE
  npm                 8.6.0        C:\Program Files\nodejs\npm.CMD
    corepack          0.10.0
    eas-cli           0.60.0
    expo-cli          6.0.1
    ignite-cli        8.2.
    npm               8.6.0
    yarn              1.22.19
  yarn                1.22.19      C:\Program Files\nodejs\yarn.CMD
    create-expo-app   1.1.1
  pnpm                -            not installed
  expo                46.0.14      managed

Ignite
  ignite-cli         8.2.         C:\Program Files\nodejs\ignite.CMD
  ignite src         src          C:\Users\Frank\Documents\GitHub\ignite-cli\src

Android
  java               -            null
  android home       -            undefined
```

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [x] `Generators.md` has been updated with changes

## Describe your PR

- Closes #2253
- This attempts to autocorrect an EOL issue with the generator template files by doing the following:
  - Checks to see if running on Windows
  - Looks for the `unix2dos` cli utility
  - If found, applies this to each of the template files found from the boilerplate
  - If not found or application fails, will output a warning at the end of terminal output to check the EOL in templates
  - Added extra debug logging
- Updated documentation to make note about this issue with Windows

## Testing

This was manually tested by doing the following:
1. Clone `ignite-cli` project on a Windows machine
2. Convert `boilerplate\ignite\templates\**\*.ts*.ejs` files EOL to LF on purpose (likely CRLF after cloning)
3. Generate a new Pizza App locally, ie:
  `node bin/ignite new PizzaWin --overwrite --debug --install-deps=false --targetPath="C:\temp\PizzaWin" --git --bundle=com.pizzawin --remove-demo=false --packager=yarn`
5. Observe that the files in the project path's `ignite\templates` has the template files with the CRLF EOL

### Terminal Warning Upon Failure

image

### Extra Debug Logging

image

### CODE REVIEW

**Comment by morganick** [comment]
I'm surprised that `git` doesn't automatically handle this with: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

File: src/commands/new.ts [hunk 1]
```diff
@@ -642,6 +678,15 @@ export default {
       p2()
     }
 
+    if (warnAboutEOL) {
+      hr()
+      p2()
+      p2(yellow(`Generator templates could not be converted to Windows EOL.`))
+      p2(yellow(`You may want to update these manually with your code editor, more info at:`))
+      p2(`${link("https://docs.infinite.red/ignite/concept/generators#windows")}`)
```
Comment (joshuayoes) [inline src/commands/new.ts:686]: This page 404s :( https://docs.infinite.red/ignite/concept/generators

File: src/commands/new.ts [hunk 2]
```diff
@@ -552,13 +553,48 @@ export default {
...
+      log(`templates to change EOL: ${templates}`)
+      if (unixToDosPath) {
+        // running the output from `which` result above seems to not work, so just pop the binary name
+        const unixToDosCmd = unixToDosPath.split("/").pop()
+        const results = await Promise.allSettled(
+          templates.map(async (file) => {
+            log(`Converting EOL for ${file}`)
+            await system.run(`${unixToDosCmd} ${file}`)
+          }),
+        )
```
Comment (joshuayoes) [inline src/commands/new.ts:578]: Nice pattern here

File: src/commands/new.ts [hunk 3]
```diff
@@ -552,13 +553,48 @@ export default {
...
+    // #region Format generator templates EOL for Windows
+    let warnAboutEOL = false
+    if (isWindows) {
+      // find unix2dos to help convert EOL, usually installed with git, ie:  C:\Program Files\Git\usr\bin\unix2dos.EXE
+      const unixToDosPath = await system.exec("which unix2dos")
+      // find all templates Ignite provides by default
+      const templates = filesystem.find(`${targetPath}/ignite/templates`, {
+        directories: false,
+        files: true,
+        matching: "*.ts*.ejs",
```
Comment (joshuayoes) [inline src/commands/new.ts:565]: I think we are going to want to use any `.ejs` file here since we can also do non-ts files. 
```suggestion
        matching: "*.ejs",
```

**Review by joshuayoes — CHANGES_REQUESTED** [review]
I love this solution. I have two small changes requested but conceptually this looks great.

File: src/commands/new.ts (hunk 1 above)
Comment (joshuayoes) [reply src/commands/new.ts:686]: We can use this for now https://github.com/infinitered/ignite/blob/master/docs/Generators.md#windows

**Comment by joshuayoes** [comment]
> I'm surprised that `git` doesn't automatically handle this with: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

This is probably because we aren't using git to copy these files over, we are essentially using copy and paste on the system.

File: src/commands/new.ts (hunk 1 above)
Comment (frankcalise) [reply src/commands/new.ts:686]: Yeah I was just planning for the future lol, but we can do where it currently lives. The link I provided banks on this getting through: https://github.com/infinitered/ignite/pull/2530

**Review by joshuayoes — APPROVED** [review]
If this PR gets merged first, looks good!
https://github.com/infinitered/ignite/pull/2540/files/782feb0ebf18cd246c4d703a10c7452a3ae45eae#r1380639904

File: src/commands/new.ts (hunk 1 above)
Comment (frankcalise) [reply src/commands/new.ts]: fixed

File: src/commands/new.ts (hunk 2 above)
Comment (frankcalise) [reply src/commands/new.ts:578]: thx, I did lift it from elsewhere in the project but yeah forEach doesn't wait up on the async calls
