### PR TITLE
Removes flow from generated app

### LINKED ISSUE #536: Flow fails on fresh initialized ignite projekt
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
Computer
  Platform: linux

Ignite
  Version: 1.12.0
  Path: /home/felix/.node_packages/bin/ignite

Node
  Version: v7.2.1
  Path: /usr/bin/node

NPM
  Version: 4.0.3
  Path: /usr/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.3.0

App
  React Native Version: 0.37.0
```
Initialized new project with:

  ignite new FlowTest

Run flow in project folder.
  yarn flow

Flow reports 109 errors mostly from within react-native. 

Expected behaviour would be that flow reports a clean folder.

### PR DESCRIPTION
**Pull request by jamonholmgren**
Removes Flow.

The generated app seems to work fine, but I am getting these warnings. Any suggestions? @GantMan 

screen shot 2017-03-03 at 12 02 57 am

Fixes #536.

### CODE REVIEW

File: packages/ignite-basic-generators/templates/examples/GridExample.js.ejs [hunk 1]
```diff
@@ -13,8 +11,8 @@ import styles from './Styles/GridExampleStyle'
 
 class GridExample extends React.Component {
 
-  state: {
-    dataSource: Object
+  state = {
```
Comment (skellock) [inline packages/ignite-basic-generators/templates/examples/GridExample.js.ejs]: These were just a an interface, you won't need to convert these.  For the state ones, I'd say lets delete them.

File: packages/ignite-dev-screens/templates/ButtonBox.js [hunk 2]
```diff
@@ -1,17 +1,14 @@
...
-type ButtonBoxProps = {
-  onPress: () => void,
-  image?: string,
-  style?: Object,
-  text?: string
-};
-
 export default class ButtonBox extends React.Component {
-  props: ButtonBoxProps
+  props = {
```
Comment (skellock) [inline packages/ignite-dev-screens/templates/ButtonBox.js]: For props, let's convert these to `static propTypes=` definitions.  If you really want, you can create a `static defaultProps` as well, but I find we rarely do this in practice.
