### PR TITLE
Fixes sporking issue, adds better tests

### LINKED ISSUE #1050: Create e2e Tests for spork functionality
it seems Spork might have broken and is reported in #1043 

We need tests to make sure we don't have this regression again.

### PR DESCRIPTION
**Pull request by jamonholmgren**
Spork was broken in `copyBatch` generators. This fixes issue #1043.

I also added an end-to-end test. The assertions can be filled out much more, but I'm happy to have what we have here. Should be very useful to catch `ignite new` issues, and it also tests a generator and of course sporking. This fixes #1050.

I also had to add the ability to specify a spork file from the initial command. Example: `ignite spork component.ejs` should spork just that file and not wait for input. Truthfully, that's how I thought it worked already!

### CODE REVIEW

File: src/extensions/ignite/copyBatch.js [hunk 1]
```diff
@@ -38,8 +47,11 @@ module.exports = (plugin, command, context) => {
       // generate the React component
       if (await shouldGenerate(job.target)) {
         const currentPluginPath = ignitePluginPath()
+
+        const sporkDirectory = findSpork(context, job.template)
+
         await template.generate({
-          directory: directory || (currentPluginPath && `${currentPluginPath}/templates`),
+          directory: directory || sporkDirectory || (currentPluginPath && `${currentPluginPath}/templates`),
```
Comment (jamonholmgren) [inline src/extensions/ignite/copyBatch.js]: I assume someone passing in `directory` should take precedence over a spork. This is an unusual circumstance, I think.

File: tests/integration/ignite-new/new.test.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+const execa = require('execa')
+const tempy = require('tempy')
+const jetpack = require('fs-jetpack')
+
+const IGNITE = `${process.cwd()}/bin/ignite`
+const APP_DIR = 'Foo'
+
+test.before(t => {
+  const tempDir = tempy.directory()
+  process.chdir(tempDir)
```
Comment (jamonholmgren) [inline tests/integration/ignite-new/new.test.js]: Now creates tests in a temporary directory, like we should have been doing all along. :)

File: tests/integration/ignite-new/new.test.js [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+})
+
+test('spins up a min app and performs various checks', async t => {
+  await execa(IGNITE, ['new', APP_DIR, '--min'])
+  process.chdir(APP_DIR)
+
+  // check the contents of ignite/ignite.json
+  const igniteJSON = jetpack.read('ignite/ignite.json')
+  t.is(typeof igniteJSON, 'string')
+  t.regex(igniteJSON, /"generators": {/)
```
Comment (skellock) [inline tests/integration/ignite-new/new.test.js]: TIL
