### PR TITLE
Fix issue #1579 -- ignite doctor on Windows -- adds optional chaining

### LINKED ISSUE #1579: Error running `ignite doctor` on Windows
Running `ignite doctor` produces the following error:

```bash
JavaScript
  node               14.15.3      C:\Users\User\scoop\apps\nodejs-lts\current\node.EXE
  npm                6.14.10      C:\Users\User\scoop\apps\nodejs-lts\current\bin\npm.CMD
  yarn               1.22.5       C:\Users\User\scoop\apps\yarn\current\Yarn\bin\yarn.CMD

Ignite
  ignite-cli         4.0.0        C:\Users\User\scoop\apps\nodejs-lts\current\bin\ignite.CMD
  ignite src         build        C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build
C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^

TypeError: Cannot read property 'slice' of null
    at Command.<anonymous> (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:152:57)
    at step (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:33:23)
    at Object.next (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:14:53)
    at fulfilled (C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli\build\commands\doctor.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

---

Steps to reproduce

1. Run: `ignite doctor`

---

### PR DESCRIPTION
**Pull request by jamonholmgren**
This PR should fix #1579 by unifying the Java command with the macOS version, and also double protection by adding optional chaining.

image

### CODE REVIEW

File: src/commands/doctor.ts [hunk 1]
```diff
@@ -90,8 +90,8 @@ module.exports = {
     // -=-=-=- android -=-=-=-
     const androidPath = process.env.ANDROID_HOME
     const javaPath = which("java")
-    const javaVersionCmd = isWindows ? "java -version" : "java -version 2>&1"
```
Comment (jamonholmgren) [inline src/commands/doctor.ts:93]: I'm not entirely sure why this was supposed to be different on Windows, but the command `java -version` resulted in a blank string, while `java -version 2>&1`  resulted in the string we wanted.

File: src/commands/doctor.ts [hunk 2]
```diff
@@ -90,8 +90,8 @@ module.exports = {
...
-    const javaVersion = javaPath && (await run(javaVersionCmd)).match(/"(.*)"/).slice(-1)[0]
```
Comment (jamonholmgren) [inline src/commands/doctor.ts:94]: Optional chaining ftw

**Comment by jamonholmgren** [comment]
Also still appears to work in macOS.

image

File: src/commands/doctor.ts (hunk 1 above)
Comment (bryanstearns) [reply src/commands/doctor.ts:93]: I didn't dig into git history (it's murky because of previous ignite rewrites) but I would've been suspicious that IO redirection might not have been a thing on Windows. Glad to hear it works and the code can be simpler!

**Review by bryanstearns — APPROVED** [review]
LGTM! 🚢
