### PR TITLE
References proper react-native binary - Fixes #949

### LINKED ISSUE #949: Error: not found: yarn
Hello,
On Win7 I followed the guide to install ignite, and I did it, but when I try to create a new project I get this error:

Error: not found: yarn

and

(node:5520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: not found: yarn

Should I install yarn? It does not say anywhere.

### PR DESCRIPTION
**Pull request by jamonholmgren**
Fixes #949

[According to @skellock](https://github.com/infinitered/ignite/issues/949#issuecomment-291283847):

> when we shell out, node is giving precedence to the node_modules/.bin/react-native executable instead of the global one on the path.

This change calls `$(which react-native) --version` rather than `react-native --version` which should address the problem in issue #949 and others.

### CODE REVIEW

**Comment by skellock** [comment]
https://github.com/npm/node-which  <-- this bad boy, right thurrr...

**Comment by jamonholmgren** [comment]
On it.

File: packages/ignite-cli/src/cli/check.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ var rnCli = enforceGlobalDependency({
   range: '>=2.0.0',
   which: 'react-native',
   packageName: 'react-native-cli',
-  versionCommand: 'react-native --version',
+  versionCommand: '--version',
```
Comment (jamonholmgren) [inline packages/ignite-cli/src/cli/check.js]: The `versionCommand` now only takes the actual version flag, not the whole command. This is because we find the executable using the new `which` call.

**Comment by jamonholmgren** [comment]
@skellock @GantMan Should be good to go now.
