### PR TITLE
Initialize git repository on Windows using separate cmds in `new` command

### LINKED ISSUE #2188: [Maverick] ignite-cli is not initializing git repository
### Describe the bug

CLI is not initializing git repository even after answering the below prompt as Yes

> Do you want to initialize a git repository? (Y/n) » Yes 

Tried with inline command, yet git was not initialized.

`npx ignite-cli@next new PizzaApp --bundle=com.pizzaapp --git --install-deps --packager=yarn`

### Ignite version

8.0.0-beta.6

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                8 cores      11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  directory          PizzaApp    C:\Users\Vijay\Desktop\PizzaApp

JavaScript (and globally-installed packages)
  node               16.17.0      C:\Program Files\nodejs\node.EXE
  npm                8.15.0       C:\Program Files\nodejs\npm.CMD
    corepack         0.12.1
    jshint           2.13.5
    npm              8.15.0
    yarn             1.22.19
  yarn               1.22.19      C:\Program Files\nodejs\yarn.CMD
    http-server      14.1.1
    localtunnel      2.0.2
  pnpm               -            not installed
  expo               46.0.10      managed

Ignite
  ignite-cli         8.0.0-beta.6   C:\Users\Vijay\AppData\Local\npm-cache\_npx\2351a7c35afcf833\node_modules\.bin\ignite.CMD
  ignite src         build          C:\Users\Vijay\AppData\Local\npm-cache\_npx\2351a7c35afcf833\node_modules\ignite-cli\build

Android
  java               17.0.4.1     C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\java.EXE
  android home       -            C:\Users\Vijay\AppData\Local\Android\Sdk
```

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant

## Describe your PR
- Fixes #2188
- Updates PR template with the correct `yarn test` command

### CODE REVIEW

File: src/commands/new.ts [hunk 1]
```diff
@@ -522,19 +522,28 @@ export default {
...
+          await system.run(log("git init"))
+          await system.run(log("git add -A"))
+          await system.run(log(`git commit -m "New Ignite ${meta.version()} app`))
+        } else {
+          await system.run(
+            log(`
+              \\rm -rf ./.git
+              git init;
+              git add -A;
+              git commit -m "New Ignite ${meta.version()} app";
```
Comment (joshuayoes) [inline src/commands/new.ts:543]: This may have to do with new line characters since windows and mac have different ones

**Review by joshuayoes — APPROVED** [review]
Tested on Windows, works like a charm!
