### PR TITLE
Removes custom metro config & symlinks if using Expo

### LINKED ISSUE #1899: Latest expo powered project is unable to build ios and android
What's going on?

--- Latest expo powered project is unable to build ios and android

error The resource `/Users/chanwoopark/projects/PizzaApp/index.js` was not found.
Error: The resource `/Users/chanwoopark/projects/PizzaApp/index.js` was not found.
    at /Users/chanwoopark/projects/PizzaApp/node_modules/metro/src/IncrementalBundler.js:457:26
    at gotStat (fs.js:1936:21)
    at FSReqCallback.oncomplete (fs.js:191:21)
    
    index.js` was not found. error occurs for both android and ios

Steps to reproduce

1. npx ignite-cli new PizzaApp --expo
2. yarn  build-ios

---

`npx ignite-cli doctor` results:

System
  platform           darwin
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  directory          PizzaApp     /Users/chanwoopark/projects/PizzaApp

JavaScript (and globally-installed packages)
  node               14.18.3      /Users/chanwoopark/.nvm/versions/node/v14.18.3/bin/node
  npm                6.14.15      /Users/chanwoopark/.nvm/versions/node/v14.18.3/bin/npm
    firebase-tools   10.1.0
    npm              6.14.15
  yarn               1.22.4       /usr/local/bin/yarn
  pnpm               -            not installed

Ignite
  ignite-cli         7.10.5       /Users/chanwoopark/.npm/_npx/93927/bin/ignite
  ignite src         build        /Users/chanwoopark/.npm/_npx/93927/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_211    /usr/bin/java
  android home       -            undefined

iOS
  xcode              13.2.1
  cocoapods          1.11.2       /usr/local/bin/pod

### LINKED ISSUE #1904: Expo publish fails on fresh install
On a brand new ignite expo project, running `expo publish` results in the following error
```
Processing asset bundle patterns:
- /Users/user/Documents/projects/PizzaApp/**/*

Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at _configureExpForAssets (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/ProjectAssets.ts:168:26)
    at exportAssetsAsync (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/ProjectAssets.ts:229:3)
    at Object.publishAsync (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/project/publishAsync.ts:93:3)
    at actionAsync (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/src/commands/publish/publishAsync.ts:103:18)
```

This is an old [expo-cli issue](https://github.com/expo/expo-cli/issues/179) but one that should not happen in newer sdk's.
Non of the solutions from the original issue works.

in app.json you can change `assetBundlePatterns` from `**/*` to `assets/*` to make it run without error, but none of the assets will be uploaded or available in the build. Furthermore the ignite boilerplate places assets in lots op places, not only in the assets folder.

Im thinking it has something to do with dependencies or babel setup 🤔
Installing a clean expo TS project (non-ignite)  with the same sdk from ignite, does not produce the error.

---

Steps to reproduce

You need to have a logged in expo account to publish.
```
npx ignite-cli new PizzaApp --expo
cd PizzaApp
expo publish
```
---

`npx ignite-cli doctor` results:

```
System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1
  directory          PizzaApp     /Users/alexanderlindkjaer/Documents/LindkjaerProjects/PizzaApp

JavaScript (and globally-installed packages)
  node               16.14.0      /Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/bin/node
  npm                8.3.1        /Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/bin/npm
    corepack         0.10.0
    expo-cli         5.2.0
    npm              8.3.1
  yarn               1.22.17      /opt/homebrew/bin/yarn
  pnpm               -            not installed

Ignite
  ignite-cli         7.10.5       /Users/alexanderlindkjaer/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/alexanderlindkjaer/.npm/_npx/e31027f378
```

### PR DESCRIPTION
**Pull request by jamonholmgren**
Fixes #1904 by removing the custom metro config file if using Expo and replacing with the default Expo metro config. Expo doesn't work with pnpm anyway, so we won't bother trying to enable symlinks if using Expo.

If you want to try @AlexanderLindkjaer's experimental symlink support, check #1904's comments.

Also fixes #1899 (I think)

### CODE REVIEW

File: src/commands/new.ts [hunk 1]
```diff
@@ -202,6 +202,10 @@ export default {
       // rename the babel.config.expo.js
       filesystem.rename("./babel.config.expo.js", "babel.config.js")
 
+      // remove the metro config js, which causes problems with publishing
+      // see: https://github.com/infinitered/ignite/issues/1904
+      filesystem.remove("./metro.config.js")
```
Comment (lindboe) [inline src/commands/new.ts:207]: Expo apps by default do have a metro config file, so I would think we'd want to preserve that instead of removing this? Looks like this is the template for it: https://github.com/expo/expo/blob/168ee43f71f005baa11edf98e518593443e1807a/templates/expo-template-bare-minimum/metro.config.js

Comment (jamonholmgren) [reply src/commands/new.ts:208]: Good point @lindboe -- just pushed up a change to address this.
