### PR TITLE
fix(boilerplate) Fix Icon Type definitions

### LINKED ISSUE #2888: Interface 'IconProps' incorrectly extends interface 'TouchableOpacityProps'
### Describe the bug

This is a typescript error on line 16 of file `src/components/Icon.tsx`. 
```
import { ComponentType } from "react"
import {
  Image,
  ImageStyle,
  StyleProp,
  TouchableOpacity,
  TouchableOpacityProps,
  View,
  ViewProps,
  ViewStyle,
} from "react-native"
import { useAppTheme } from "@/utils/useAppTheme"

export type IconTypes = keyof typeof iconRegistry

interface IconProps extends TouchableOpacityProps {
  /**
   * The name of the icon
   */
  icon: IconTypes

  /**
   * An optional tint color for the icon
   */
  color?: string

  /**
   * An optional size for the icon. If not provided, the icon will be sized to the icon's resolution.
   */
  size?: number

  /**
   * Style overrides for the icon image
   */
  style?: StyleProp<ImageStyle>

  /**
   * Style overrides for the icon container
   */
  containerStyle?: StyleProp<ViewStyle>

  /**
   * An optional function to be called when the icon is pressed
   */
  onPress?: TouchableOpacityProps["onPress"]
}
...
```
The property in question is probably
```
  /**
   * Style overrides for the icon image
   */
  style?: StyleProp<ImageStyle>
```
The error message:
```
ts: Interface 'IconProps' incorrectly extends interface 'TouchableOpacityProps'.
  Types of property 'style' are incompatible.
    Type 'StyleProp<ImageStyle>' is not assignable to type 'StyleProp<ViewStyle>'.
      Type 'ImageStyle' is not assignable to type 'StyleProp<ViewStyle>'.
        Type 'ImageStyle' is not assignable to type 'ViewStyle'.
          Types of property 'transformOrigin' are incompatible.
            Type 'string | (string | number)[] | undefined' is not assignable to type 'string | undefined'.
              Type '(string | number)[]' is not assignable to type 'string'. [2430]
```
I never touched this file.

### Ignite version

release

### Additional info

```
?master ~/spaces/rn/IgniteTrivia> npx ignite-cli doctor
System
  platform           linux
  arch               x64
  cpu                12 cores       AMD Ryzen 5 5600G with Radeon Graphics
  directory          IgniteTrivia   /home/alexey/spaces/rn/IgniteTrivia

JavaScript (and globally-installed packages)
  node               22.13.0                                   /home/alexey/.local/share/mise/installs/node/22.13/bin/node
  npm                10.9.2                                    /home/alexey/.local/share/mise/installs/node/22.13/bin/npm
    corepack         0.30.0
    npm              10.9.2
  yarn               1.22.22                                   /home/alexey/.local/share/mise/installs/yarn/1/bin/yarn
  pnpm               9.12.3                                    /home/alexey/.local/share/mise/installs/pnpm/9.12.3/bin/pnpm
                     <no pnpm global package info available>
  bun                -                                         not installed
  expo               52.0.25                                   managed

Ignite
  ignite-cli         10.1.4       /home/alexey/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /home/alexey/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               17.0.13      /usr/bin/java
  android home       -            /opt/android-sdk

Tools
  git                git version 2.47.1   /usr/bin/git
?master ~/spaces/rn/IgniteTrivia>
```

### PR DESCRIPTION
**Pull request by silasjmatson**
## Description

There were two issues at play here:

1. Icon's `style` prop overrides the Wrapped `TouchableOpacity`'s `style` prop with an incompatible `StyleProp<ImageStyle>`
2. Icon changed the wrapper used based on the presence of the `onPress` prop, which made accurate typing and linting difficult.

See
https://github.com/infinitered/ignite/issues/2888#issuecomment-2738096598 for more information.

This commit fixes #2888 by simply separating `Icon` into `PressableIcon` and `Icon` components, with simplified prop types for each, and updates the docs to reflect the change.

- Issues:  #2888 

## Checklist

- [x] `README.md` and other relevant documentation has been updated with my changes

### CODE REVIEW

File: boilerplate/app/components/Icon.tsx [hunk 1]
```diff
@@ -38,16 +38,47 @@ interface IconProps extends TouchableOpacityProps {
...
-  onPress?: TouchableOpacityProps["onPress"]
+type PressableIconProps = Omit<TouchableOpacityProps, "style"> & BaseIconProps
+type IconProps = Omit<ViewProps, "style"> & BaseIconProps
+
+/**
+ * A component to render a registered icon.
+ * It is wrapped in a <TouchableOpacity />
+ * @see [Documentation and Examples]{@link https://docs.infinite.red/ignite-cli/boilerplate/app/components/Icon/}
+ * @param {IconProps} props - The props for the `Icon` component.
+ * @returns {JSX.Element} The rendered `Icon` component.
```
Comment (silasjmatson) [inline boilerplate/app/components/Icon.tsx:51]: TODO: update these to reference the `PressableIcon`

File: docs/boilerplate/app/components/Icon.md [hunk 2]
```diff
@@ -4,12 +4,16 @@ sidebar_position: 35
 
 # Icon
 
-Ignite's `Icon` Component renders an icon using predefined icon images. You can use those, override them, or customize this component to create any number of image based icons. If `onPress` is passed, it will wrap the icon in a [`TouchableOpacity`](https://reactnative.dev/docs/touchableopacity) component, otherwise it will use a [`View`](https://reactnative.dev/docs/view) component.
+Ignite's `Icon` and `PressableIcon` Components renders an icon using predefined icon images. You can use those, override them, or customize this component to create any number of image based icons. `PressableIcon` will wrap the icon in a [`TouchableOpacity`](https://reactnative.dev/docs/touchableopacity) component, `Icon` will use a [`View`](https://reactnative.dev/docs/view) component.
```
Comment (silasjmatson) [inline docs/boilerplate/app/components/Icon.md:7]: subject-verb disagreement

File: boilerplate/app/components/Icon.tsx [hunk 3]
```diff
@@ -38,16 +37,47 @@ interface IconProps extends TouchableOpacityProps {
...
+ * @returns {JSX.Element} The rendered `PressableIcon` component.
+ */
+export function PressableIcon(props: PressableIconProps) {
+  const {
+    icon,
+    color,
+    size,
+    style: $imageStyleOverride,
+    containerStyle: $containerStyleOverride,
+    ...WrapperProps
```
Comment (robinheinze) [inline boilerplate/app/components/Icon.tsx:59]: We can probably rename this spread variable "pressableProps" since there's not the concept of a generic wrapper anymore

**Review by frankcalise — APPROVED** [review]
Nice work!

File: docs/boilerplate/app/components/Icon.md [hunk 4]
```diff
@@ -71,18 +75,18 @@ The `style` prop is optional. This is an object that overrides the default style
...
 ```
 
 ### `onPress`
 
-The `onPress` optional prop is a function that will be called when the icon is pressed. Note that when this prop is passed, the icon will be wrapped in a `TouchableOpacity` component rather than a `View` component.
+The `onPress` prop can be passed to a `PressableIcon` Component, which will forward it to the wrapped `TouchableOpacity`s `onPress` prop.
 
 ```tsx
-<Icon icon="ladybug" onPress={() => Alert.alert("Hello")} />
+<PressableIconIcon icon="ladybug" onPress={() => Alert.alert("Hello")} />
```
Comment (silasjmatson) [inline docs/boilerplate/app/components/Icon.md:89]: whoops
