### PR TITLE
demo screen fix drawer opened by default

### LINKED ISSUE #2535: Demo screen : drawer opens unexpectedly on mount due to route.params check always truthy inside useEffect
### Describe the bug

When the screen demo loads, the drawer opens by default. I've traced this behaviour to the handleScroll function being triggered by a React.useEffect block. Within this block, toggleDrawer gets called, changing the drawer's open/close state. The root cause seems to be the condition if (route.params) in the useEffect, which evaluates to true even when route.params is an empty object.

### Ignite version

8.9.3

### Additional info

Inside the useEffect  changing the condition to be `Object.keys(route.params).length > 0` fix the problem

### PR DESCRIPTION
**Pull request by ludocourbin**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR

Fix demo screen : drawer opens unexpectedly on mount due to route.params check always truthy inside useEffect

close #2535

### CODE REVIEW

File: boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ export const DemoShowroomScreen: FC<DemoTabScreenProps<"DemoShowroom">> =
 
     // handle Web links
     React.useEffect(() => {
-      if (route.params) {
+      if (Object.keys(route.params).length > 0) {
```
Comment (frankcalise) [inline boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx:100]: let's add a `Platform.OS` check for web here because it still remains open on mobile from what I tested.

**Review by frankcalise — CHANGES_REQUESTED** [review]
Hey thanks for the contribution! Left one comment after some testing.

Also if you wouldn't mind updating line 100 to params and switching that in the dependency array that would be helpful I think - or change everything to route.params and wipe out 96 for consistency.

File: boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx (hunk 1 above)
Comment (ludocourbin) [reply boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx]: It appears to work as intended in mobile for me, can you guide me to how you tested ? i'm relatively new to using expo and react-native

Comment (frankcalise) [reply boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx]: @ludocourbin I was testing with `npx ignite-cli@next`, let me try it again with the master version and if that works I can make the necessary updates for next as a follow-up

Comment (ludocourbin) [reply boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx]: Perfect, thank you

**Review by frankcalise — CHANGES_REQUESTED** [review]
We probably need to update the dependency array here now to match `params`

**Review by frankcalise — APPROVED** [review]
Thank you for your contribution!

**Comment by ludocourbin** [comment]
> Thank you for your contribution!

Thank you for your help
